# try:
#     global_var=20 # its global variable
#     def fun():
#         local_var=10 # its local var it created in the function
#         print(local_var)
#     global_var2=30 # its global var
#     #print(local_var)
# except Exception as e:
#     print(e)

#created the global and local variables and calling it

# global_var=20 # its global variable
# def fun():
#     local_var=10 # its local var it created in the function
#     print(local_var)
#     print(global_var)
# global_var2=30 # its global var
# print(global_var2)
#fun()

# create the same name of variables and call it who calls first
# xy=10
# def fun():
#     xy=20
#     print(xy)
# fun()
#local avr is alawys call fisrt

# create the global variable and try to access the with in function
# xy=100
# def fun():
#     global xy
#     xy=200
#     print(xy)
# fun()
# print(xy)

# try:
#     xy=100
#     def fun():
#         global xy
#         xy=200 #### this is correct
#         print(xy)
#     fun()
#     print(xy)
# except Exception as e:
#     print(e)

# creating the global variables inside of the function
# def fun():
#     global xy
#     xy=200
#     print(xy)
# fun()
# print(xy)



